/**
 * Dog breeds for the booking form's type-ahead.
 *
 * Bundled rather than fetched: it's a small static list, it costs nothing, it
 * works offline, and it can't break the booking form if a third party is down.
 *
 * Includes the popular crossbreeds (Cockapoo, Labradoodle, Cavapoo…) alongside
 * Kennel Club breeds — for a groomer those are among the most common bookings,
 * and their coats are exactly the ones that drive price and time.
 *
 * The field is informational, so anything not on the list can still be typed
 * freely — the list is a convenience, never a restriction.
 */
export const DOG_BREEDS: readonly string[] = [
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "American Bulldog",
  "American Cocker Spaniel",
  "Australian Cattle Dog",
  "Australian Shepherd",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Bearded Collie",
  "Bedlington Terrier",
  "Belgian Malinois",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Bloodhound",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bouvier des Flandres",
  "Boxer",
  "Bracco Italiano",
  "Briard",
  "Brittany",
  "Bull Terrier",
  "Bullmastiff",
  "Cairn Terrier",
  "Cane Corso",
  "Cavachon",
  "Cavalier King Charles Spaniel",
  "Cavapoo",
  "Chihuahua",
  "Chinese Crested",
  "Chow Chow",
  "Clumber Spaniel",
  "Cockapoo",
  "Cocker Spaniel",
  "Collie (Rough)",
  "Collie (Smooth)",
  "Corgi (Cardigan Welsh)",
  "Corgi (Pembroke Welsh)",
  "Curly Coated Retriever",
  "Dachshund (Long Haired)",
  "Dachshund (Smooth Haired)",
  "Dachshund (Wire Haired)",
  "Dalmatian",
  "Dandie Dinmont Terrier",
  "Deerhound",
  "Doberman Pinscher",
  "Dogue de Bordeaux",
  "English Bulldog",
  "English Setter",
  "English Springer Spaniel",
  "English Toy Terrier",
  "Estrela Mountain Dog",
  "Field Spaniel",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Flat Coated Retriever",
  "Fox Terrier (Smooth)",
  "Fox Terrier (Wire)",
  "Foxhound",
  "French Bulldog",
  "German Pointer (Shorthaired)",
  "German Pointer (Wirehaired)",
  "German Shepherd",
  "German Spitz",
  "Giant Schnauzer",
  "Glen of Imaal Terrier",
  "Golden Retriever",
  "Goldendoodle",
  "Gordon Setter",
  "Great Dane",
  "Greyhound",
  "Griffon Bruxellois",
  "Hamiltonstovare",
  "Havanese",
  "Hungarian Puli",
  "Hungarian Vizsla",
  "Hungarian Wirehaired Vizsla",
  "Ibizan Hound",
  "Irish Setter",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Italian Spinone",
  "Jack Russell Terrier",
  "Japanese Chin",
  "Japanese Shiba Inu",
  "Japanese Spitz",
  "Keeshond",
  "Kerry Blue Terrier",
  "King Charles Spaniel",
  "Komondor",
  "Labradoodle",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Lakeland Terrier",
  "Lancashire Heeler",
  "Leonberger",
  "Lhasa Apso",
  "Lowchen",
  "Maltese",
  "Maltipoo",
  "Manchester Terrier",
  "Mastiff",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Newfoundland",
  "Norfolk Terrier",
  "Norwegian Buhund",
  "Norwegian Elkhound",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Old English Sheepdog",
  "Otterhound",
  "Papillon",
  "Parson Russell Terrier",
  "Pekingese",
  "Pointer",
  "Polish Lowland Sheepdog",
  "Pomeranian",
  "Pomsky",
  "Poodle (Miniature)",
  "Poodle (Standard)",
  "Poodle (Toy)",
  "Portuguese Water Dog",
  "Pug",
  "Pyrenean Mountain Dog",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Russian Black Terrier",
  "Saint Bernard",
  "Saluki",
  "Samoyed",
  "Schipperke",
  "Schnauzer (Standard)",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Shar Pei",
  "Sheepadoodle",
  "Shetland Sheepdog",
  "Shih Tzu",
  "Siberian Husky",
  "Silky Terrier",
  "Skye Terrier",
  "Sloughi",
  "Soft Coated Wheaten Terrier",
  "Springador",
  "Staffordshire Bull Terrier",
  "Sussex Spaniel",
  "Swedish Vallhund",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Weimaraner",
  "Welsh Springer Spaniel",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Whippet",
  "Whoodle",
  "Yorkipoo",
  "Yorkshire Terrier",
  "Crossbreed / Mixed",
  "Unknown",
];

/** Separator used when a pet is a cross of two breeds. */
export const BREED_CROSS_SEPARATOR = " × ";

/**
 * Combines the breed inputs into the single value stored on the booking.
 * Kept in one place so the booking form and anything reading it later agree
 * on the format.
 */
export function combineBreeds(
  primary: string | null,
  secondary: string | null
): string | null {
  const a = primary?.trim() || "";
  const b = secondary?.trim() || "";
  if (!a && !b) return null;
  if (!a) return b;
  if (!b) return a;
  if (a.toLowerCase() === b.toLowerCase()) return a;
  return `${a}${BREED_CROSS_SEPARATOR}${b}`;
}
