-- Groomies · Migration 001
-- Core helpers, profiles (owner/staff), business_settings singleton, services.
--
-- Conventions:
--   * All timestamps are timestamptz (Postgres stores UTC internally).
--   * Europe/London is the business timezone — see helpers below.
--   * Money is stored in integer cents to avoid float rounding.
--   * Enums are modelled as check constraints on text for evolvability.
--   * Primary keys are UUIDs generated by pgcrypto.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Timezone helpers
-- ---------------------------------------------------------------------------

-- Today's date in the business timezone (handles GMT⇄BST correctly).
-- Used anywhere we compare a `date` column to "today".
create or replace function public.today_london()
returns date
language sql
stable
as $$
  select (now() at time zone 'Europe/London')::date
$$;

-- ---------------------------------------------------------------------------
-- Generic updated_at trigger
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ---------------------------------------------------------------------------
-- profiles — staff/owner accounts (customers do NOT get profile rows)
-- ---------------------------------------------------------------------------
--
-- Role-aware from day one. Launch will contain a single `owner` row.
-- RLS policies check "is this an active profile, and what role" — never a
-- hardcoded admin id.

create table public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  full_name   text not null,
  role        text not null check (role in ('owner', 'staff')),
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

comment on table public.profiles is
  'Staff accounts. auth.users → profiles is 1:1 for staff/owners; customers have no row here.';

-- ---------------------------------------------------------------------------
-- Role-check helpers (used by RLS policies in a later migration)
-- ---------------------------------------------------------------------------

-- Returns the role of the currently authenticated user, or null if they are
-- either unauthenticated, have no profile, or their profile is inactive.
create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
    from public.profiles
   where id = auth.uid()
     and is_active = true
$$;

create or replace function public.is_active_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
     where id = auth.uid()
       and is_active = true
  )
$$;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
     where id = auth.uid()
       and role = 'owner'
       and is_active = true
  )
$$;

-- Lock the helpers down: only authenticated calls need them.
revoke execute on function public.current_user_role() from public;
revoke execute on function public.is_active_staff() from public;
revoke execute on function public.is_owner() from public;
grant  execute on function public.current_user_role() to authenticated;
grant  execute on function public.is_active_staff() to authenticated;
grant  execute on function public.is_owner() to authenticated;

-- ---------------------------------------------------------------------------
-- business_settings — single-row, owner-editable
-- ---------------------------------------------------------------------------
--
-- The trick: `id boolean primary key check (id)` means there can only ever be
-- one row (id must be true and unique). The public site reads from this table
-- for branding, contact info, SEO, etc. — nothing brand-related is hardcoded.

create table public.business_settings (
  id                             boolean primary key default true check (id),

  -- branding & contact
  business_name                  text not null default 'Groomies',
  logo_url                       text,
  contact_phone                  text,
  contact_email                  text,
  about_blurb                    text,
  social_links                   jsonb not null default '{}'::jsonb,
  primary_brand_color            text,
  default_service_area_copy      text,

  -- notification routing
  owner_notification_email       text,
  technical_billing_alert_email  text,

  -- payments
  payments_enabled               boolean not null default false,
  deposit_mode                   text not null default 'off'
                                   check (deposit_mode in ('off', 'deposit', 'full')),

  -- policies
  retention_months               integer not null default 12
                                   check (retention_months between 1 and 60),
  refund_cutoff_hours            integer not null default 48
                                   check (refund_cutoff_hours between 0 and 168),
  hold_duration_minutes          integer not null default 15
                                   check (hold_duration_minutes between 5 and 60),

  created_at                     timestamptz not null default now(),
  updated_at                     timestamptz not null default now()
);

create trigger business_settings_set_updated_at
before update on public.business_settings
for each row execute function public.set_updated_at();

-- Seed the single row so the app never has to handle "no settings yet".
insert into public.business_settings (id) values (true);

comment on table public.business_settings is
  'Single-row table (id=true). Owner-editable branding, policies, and toggles.';

-- ---------------------------------------------------------------------------
-- services — groom types (name, duration, price, optional deposit)
-- ---------------------------------------------------------------------------
--
-- duration_minutes is informational only — it does NOT drive slot sizing. Slot
-- capacity is controlled per time_slot in a later migration.

create table public.services (
  id                    uuid primary key default gen_random_uuid(),
  name                  text not null,
  description           text,
  duration_minutes      integer not null check (duration_minutes > 0),
  price_cents           integer not null check (price_cents >= 0),
  deposit_amount_cents  integer check (deposit_amount_cents is null or deposit_amount_cents >= 0),
  is_active             boolean not null default true,
  sort_order            integer not null default 0,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create trigger services_set_updated_at
before update on public.services
for each row execute function public.set_updated_at();

create index services_active_sort_idx
  on public.services (is_active, sort_order);

comment on column public.services.duration_minutes is
  'Informational only — shown to customer, helps owner plan. Does NOT drive scheduling.';
comment on column public.services.price_cents is
  'Price in integer cents (never floats).';
